// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MonoRemoteDebugger.VSExtension
{
    static class Vsix
    {
        public const string Id = "27D183E9-5D2B-44D6-9EC8-2DB329096DF7";
        public const string Name = "MonoRemoteDebugger";
        public const string Description = @"MonoRemoteDebugger";
        public const string Language = "en-US";
        public const string Version = "1.4.0";
        public const string Author = "Techl.com";
        public const string Tags = "mono, debugger, remote";
    }
}
